### ISSUE TITLE
Refactor Search functionality to reduce bloat

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#102]
Presently, the Search functionality has too much code written for something trivial:
- Close to 5 models
- A controller with many private methods
- Many helpers

Actually, Sunspot-Solr itself comes with an elegant [Query builder](http://ruby-doc.org/gems/docs/n/nxa-sunspot-0.10.7/Sunspot/Search.html), so all these abstractions `SearchService`, `SearchCriteria`, `SearchQuery`, etc, etc are unnecessary. Refactor this to reduce the code a lot.

**Comment by rdsubhas** [comment]
Already the Query Builder has been kickstarted as part of #40 need to use the same for Advanced Search as well.

**Comment by rdsubhas** [comment]
##### Open Items:
- [x] Update Wiki
- [x] For Production, use only one core instead of unnecessary 4 cores. This doesn't impact functionality in any way, but good to optimize
- [x] Rarely, we sometimes get some exceptions related to stale PIDs or corrupted Data directories. Need some task like the old `clean_start` which completely kills all running Solr processes, clears the data directory, starts Solr and does the reindexing. With the new version of Solr, this may not be required, but still making a note in case someone comes across the bug - **This is no longer required** since we switched to Docker and there is no statefulness anymore
- [x] Add utility `sunspot:check` rake task, to check whether sunspot is running or not, and can be used as a dependency for cucumber and rspec rake tasks. It can still be tackled with the wiki, but making a note
- [x] Figure out PID files for dev.rapidftr.com and test.rapidftr.com
- [x] Make sure the new EdgeNGramsFilter and PhoneticFilter don't make the search too fuzzy, and end up messing up Combo box searches (e.g. matching `Male` inside both `Male/Female`, matching `Verified` inside both `Verified/Unverified`, etc)

**Comment by tomclement** [comment]
@rdsubhas - checked. Works as expected on the web. On the mobile we have that fuzziness showing up, but I think given the restrictions we have on the mobile that should be ok.

**Comment by rdsubhas** [comment]
Excellent :) Thanks @tomclement
