### ISSUE TITLE
Provide option to set up users and roles at first time set up

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#135]
This release of RapidFTR will enable a SYS ADMIN choose whether to use default users and roles or set up their own roles and users

**Comment by baziwane** [comment]
We expect a wizard kind of set up that will have the following stages:
- [ ] Create an Administrator account
       - Username
       - Password
       - Confirm Password
- [ ] Would you like to use Standard Roles and Users
      - Yes
      - No
- [ ] If Yes, Select Standard Roles & Users
      - [ ] Field Worker
      - [ ] Field Admin
- [ ] If No, Proceed to Next Step
- [ ] Display form to create new users and assign roles
