### ISSUE TITLE
Chef Deployment (Cloud)

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#147]

**Comment by rdsubhas** [comment]
Objective:
- Single-click Cloud deployment (Development - dev/test/uat AND Production nu/uw/etc)

#### Tasks:
- [x] Setup a VM with Docker
- [x] Setup Jenkins and Jenkins Slave
- [x] Configure Security
- [x] When Docker build is complete, trigger Jenkins. Done, it is triggered purely using HTTPS since only HTTPS is exposed.
- [x] Add uat.rapidftr.com
- [ ] Add demo.rapidftr.com. **MOVE** to separate card called "Run multiple RapidFTR in same server"
- [ ] Add uganda.rapidftr.com. **NOTE** not sure whether uganda.rapidftr.com is used anymore
