### ISSUE TITLE
Add/view a single enquiry on web

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#151]
Enquiries enable a parent searching for their missing child to register their request and trigger family tracing and reunification processes. In order to achieve this, field workers must complete a series of form fields containing information related to the child and parent and saving this for processing. The current implementation of RapidFTR only supports registration of enquiries on mobile. The purpose of this feature is to enhance the system to support registration of enquiries for users with netbooks, desktops and other browser based devices. To add an enquiry, a field worker shall click on a Register New Enquiry button, which will display a page containing a form, complete necessary fields in the form, save it and finally be able to view the completed enquiry in readonly/view only format on their screen.

**Comment by baziwane** [comment]
GIVEN that I AM A USER 
AND I have correct permissions to register enquiries
WHEN I log into RapidFTR
THEN I should be able to view a link "Register New Enquiry" on the landing page.

GIVEN that I AM A USER 
AND I have correct permissions to register enquiries
WHEN I navigate to the register new enquiries page
THEN I should be able to view the enquiries form with all form sections and fields as defined in the form builder
AND I should be able to view a save button

GIVEN that I AM A USER
AND I have the correct permissions to register enquiries
WHEN I click on the save button
THEN I should be able to view a success message at the top of the page indicating that my enquiry was successfully saved

Rule
[ ] at least one field completed for save
[ ] view form in view only format (with completed fields) after save
[ ] display fields in form sections

**Comment by ctumwebaze** [comment]
Tasks
- [x] Add "Register New Enquiry" on the landing page that points to the new enquiry page.
- [x] Add form to handle creation of enquiries with the defined form sections
  - [x] Refactor the field & form section partials to be used for the enquiries as well
  - [x] render the same form page if the enquiry contains invalid data
- [x] Viewing a single enquiry after creation (After the user has created a single enquiry they should be redirected to the single enquiry view)
- [x] Ensure that only user with the required permissions can create enquiries.
- [ ] Add audit fields to the enquiry entity (see CouchREST Timestamps)

**Comment by baziwane** [comment]
Tracking support for photos and audio in #174
