### ISSUE TITLE
Sync all enquiries with server/netbook

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#152]

**Comment by ctumwebaze** [comment]
Tasks
- [x] Change the way Enquiries are saved on the Mobile
- [x] Remove the Criteria on the Enquiry
- [x] Send the Records from the Mobile to the server in the right format.
- [x] Process Enquiries on the server
  - [x] Create Criteria from Enquiry
  - [x] Save the Enquiry
  - [x] Verify that the Criteria is Fed  into Solr
