### ISSUE TITLE
Production deployment (Test upgrade with clickable deployment)

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#153]
@scampo, this will require an actual production instance to pull off. This would complete #147 
- [ ] Data migration required for servers with existing data
  - [x] Images and attachments should migrate
  - [ ] Child data should migrate (broken after form builder refresh)
  - [ ] Forms should migrate (broken after form builder refresh)
  - [ ] Users and Roles should migrate (not affected yet)

**Comment by scampo** [comment]
Let's discuss on Monday which instance to use.
-   ___________________ Stuart CampoInnovation Unit, UNICEF
  scampo@unicef.org scampo@unicef.org +254.718.764526 (Kenya)
  +211.921.379121 (South Sudan) +256.779.234347 (Uganda) +1.802.249.8233
  (U.S.) Skype: stuart.campo  *currently in the UK, available on
  +447845511169    www.unicefstories.org http://www.unicefstories.org
  *

**Comment by baziwane** [comment]
Include #167 as a task on this card

New Form Builder has Form > Form Section > Field.

Old Form Builder has only Form Section > Field.

Make sure to write migrations for the old data.

Pinging @baziwane to take a look at this story as well. If there is any "Ensure Backwards Compatibility" story, this can also be added as a sub-task of that.
