### ISSUE TITLE
Upgrade Rails, CouchDb and Ruby Tech Stack

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#26]
- [x] Upgrade to Rails 4 for security updates
- [x] Upgrade to Ruby 2.0 for security updates
- [x] Upgrade CouchDB and related plugins

**Comment by rdsubhas** [comment]
##### Tasks:
- [x] Merge quoin/rapidftr
- [x] Make Unit tests pass
- [x] Make Headless tests pass
- [x] Make Browser tests pass
- [ ] Test major functionality
  - [x] Exports (PDF, XLS, Encryption)
  - [x] Image rotation and resizing
    - [ ] Old image data not migrating
  - [x] Advanced Search
  - [ ] Server-to-server Sync
  - [ ] Mobile/API, DB Keys, etc
  - [x] Encrypted cookies
  - [ ] Scheduler
  - [ ] Anything else?
- [ ] Improve/Refactor deprecated parts wherever necessary
- [x] Fix Chef scripts
- [ ] Make deployable to dev/test/uat

**Comment by ctumwebaze** [comment]
i had bundle 1.5.0 installed on my machine and when i run bundle install i was getting some errors of failure to find some gems. So i upgraded my bundle version to the latest i.e. 1.6.3 as of this writing.

**Comment by ctumwebaze** [comment]
some migrations fail when i run RAILS_ENV=test bundle exec rails app:reset 
The particular migration that failed is db/migration/0011_add_date_of_separation_to_separation_history_form_section.rb

**Comment by rdsubhas** [comment]
Open issues:
- [ ] No error messages in logs (rescue_from is gobbling errors)
- [ ] Images are getting corrupted when migrating

**Comment by tomclement** [comment]
We still have to: 
- [x] Update the [wiki](https://github.com/rapidftr/RapidFTR/wiki) particularly in regard to the steps required to start Solr and the Scheduler
