### ISSUE TITLE
Provide option to choose standard forms at first time use

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#48]
This release of RapidFTR will enable a SYS ADMIN choose whether to use standard set of forms or define/customise their own set of forms during deployment. This feature will include implementation of the steps necessary to achieve this set up.
After using the installer to set up RapidFTR, the admin would access the URL to the server instance and immediately be provided with options to configure the instance.

**Comment by baziwane** [comment]
We expect a wizard kind of set up that will have the following stages:
- [ ] Would you like to use Standard/Default RapidFTR Forms
      - Yes
      - No
- [ ] If Yes, Select Standard Forms & Fields
      - [ ] Basic Information
      - [ ] Etc
- [ ] If No, Proceed to Next Step
- [ ] Login

**Comment by austiine04** [comment]
##### Tasks:

Functionality to add a new standard form sections. Basically list of standard form sections with their fields and user can select with form sections and fields that they want.
- [x] Seed only users & roles, don't seed form sections
- [x] Make `lib/.../form_section_setup` return only array of forms, don't create them immediately
- [x] Add button called "Add Standard Forms" in the "Forms" page
- [x] Show standard form sections & fields (from `lib/.../form_section_setup`) in the below kind of format:
  - [x] Basic Identity
    - [x] Name
    - [x] Gender
    - [ ] ...
  - [ ] Family Details
    - [ ] ...
    - [ ] ...
- [x] Allow user to pick what standard forms & fields that he/she wants
- [x] After saving, create only those selected forms & fields

##### Additional Tasks:
- [ ] Pending

**Comment by tomclement** [comment]
Blocked due to rapidftr/tracker/issues/170

**Comment by tomclement** [comment]
Resolved with rapidftr/RapidFTR#697
