### ISSUE TITLE
Docker for Cloud Deployment (Server/Netbook)

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#51]
@rdsubhas provided context on the mailing list on why we chose to shift to docker:

https://groups.google.com/d/msg/rapidftr/gbIw6xfMDXk/HvaDSzHs_N4J

**Comment by rdsubhas** [comment]
##### Tasks:
- [x] Make Docker use latest Solr
- [x] Persist data in container (couchdb data, couchdb username/password?)
- [x] Call reindex when solr starts
- [x] Add HTTPS support to nginx
- [x] Add HTTPS support to couchdb (added using nginx reverse proxy for SSL termination)
- [x] Use Chef to orchestrate/manage deployments
  - [x] Add Librarian-Chef for docker cookbook
  - [x] Cleanup old, unused docker images after upgrading
- [x] Update Snap-CI

**Comment by ctumwebaze** [comment]
A little documentation for this story is at https://github.com/rapidftr/RapidFTR/wiki/Continuous-Integration 

This is a living document as can be improved as need arises.

**Comment by rdsubhas** [comment]
Doc looks nice :)
