### ISSUE TITLE
Order matched records by relevance

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#65]
Ordering matched records by relevance ensures that matches are displayed in order of highest degree of field matches found in a child record. This issue is dependent on #187.
Key considerations:
- Display the degree of matching of each match (depends on method chosen - boosting vs proximity matching)
- Displaying a limited number of results

**Comment by baziwane** [comment]
GIVEN that I AM A FIELD WORKER
WHEN I am viewing the list of potential matches in my browser
THEN I should be able to view the degree of matching for each record

GIVEN that I AM an ADMIN
WHEN I am setting up  RapidFTR
THEN I should be able to set the cut off score

**Comment by ctumwebaze** [comment]
Tasks
- [x]  Add score to the potential matches model
- [x] Display score on the potential matches summary view
- [x] sort the potential matches based on the scores in descending order
- [x] Update the score for potential matches that already exist.
- [x] Add interface to allow the administrator set a score threshold
- [x] Limit the number of results based on a predefined score e.g. any match whose score is lower than say 0.2 will not be returned.
- [x] ?Mark as Deleted potential Matches that are not marked as invalid or confirmed when the administrator changes the matching threshold.
- [x] ?Mark as Deleted Potential Matches whose score goes below the set threshold when the user changes the records and a search is made for potential matches.
- [ ] Document how this feature works.
- [x] For existing potential matches that have been marked deleted, unmark them when they re-appear in the solr hits
- [x] Ensure when the mobile receives the potential matches that are marked as deleted, it should delete them from the device.

**Comment by mwangiann** [comment]
How it works:

On the web:
  The admin will put up a score threshold for the enquiries, this is the lower limit to the score that each returned potential match should have. The score is displayed below the image of each potential match. 
  After each search, the children matching the enquiries will only be those above the set threshold value. This value can be changed anytime by the admin.

On the mobile:
  When a user logs into the mobile and syncs, they should only see the potential matches that are above the threshold, but the score is not displayed here.

**Comment by tomclement** [comment]
~~Updates to the score on corresponding enquiries are not being triggered when changes are made to child records. Look at https://github.com/rapidftr/tracker/issues/228~~

**[Update]** This issue is now resolved with https://github.com/rapidftr/RapidFTR/pull/758

**Comment by tomclement** [comment]
After interacting with the potential matches feature using various datasets, it was noticed that some of the records appearing among the potential matches had no obvious attributes matching the search queries. For example an enquiry search for a child named "John" might present as a potential match a child record with absolutely no field with the text "John". This was particularly exhibited in the fact that on creating different child records with exactly the same field values, when these records appeared as potential matches they would most often have varying scores (indicating that solr had ranked them differently).

It turns out that solr is actually performing searches for potential matches even across the system fields such as `unique_identifier` and `short_id` (see snippet below which shows the attributes of the child records in a particular dataset that were matched by solr for the query `Doe`):

```
Name Child001 - Score 5.7478657 - Highlights:
*708d0a4*
Name Child001 - Score 5.309651 - Highlights:
*622808d3*-fd77-45ed-b210-bd04dda3243d
*da3243*d
Name Child001 - Score 4.5982924 - Highlights:
*6d642*d3
Name Child001 - Score 3.3185318 - Highlights:
*06e69d9*
Name Child001 - Score 2.6917293 - Highlights:
314e1973-*9d6a*-4abe-8b87-*459a0edee34*c
Name Child001 - Score 2.6917293 - Highlights:
f073d120-*d510*-*4d96*-89f8-*55d5*c5f4529b
Name Jane Doe - Score 2.6548254 - Highlights:
59a59604-5517-44ee-a597-*da8*fd96d2d28
*96d2*d28
Jane *Doe*
Name John Doe - Score 2.4757628 - Highlights:
John *Doe*
Name Child001 - Score 2.1977878 - Highlights:
87227711-9b16-4b74-9fdf-*72d7e56*c0ab3
Name Child001 - Score 1.0988939 - Highlights:
07fec47f-1b81-435f-95fb-*061d4*fbecb0d
```

To combat this issue, solr's search scope should be limited away from the system fields. Tracking this in https://github.com/rapidftr/tracker/issues/230

**Comment by andreweskeclarke** [comment]
Should we let users select "matchable" fields for Children, or just omit system fields?

**Comment by tomclement** [comment]
Users will select 'matchable' fields for children. Tracking this in https://github.com/rapidftr/tracker/issues/235

**Comment by tomclement** [comment]
Blocked due to https://github.com/rapidftr/tracker/issues/236

**Comment by tomclement** [comment]
Blockers resolved
