### ISSUE TITLE
Tag the corresponding enquiry as 'Reunited' when marking a child as Reunited

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#67]

**Comment by baziwane** [comment]
Hi @scampo, some questions regarding this feature:
- Only enquiries that are confirmed matches to the child record will be "closed"? 
- Is "Closed" the correct term used by child protection specialists for such enquiries (if we use the same term will it be clear to them)?
- Does closing an enquiry means it no longer appears in list of potential matches for other child records?
- A change log is added to both child record and enquiries?
- Affected enquiries  can still show up in search results?
- Should a field worker be able to edit the enquiry (I noticed the child record is still editable)?

**Comment by baziwane** [comment]
From RapidFTR perspective, we're assuming that Reunification has happened (all relevant forms have been completed, verified and possibly child also physically reunified with parent/guardian). At this point, the field worker would access RapidFTR and flag the child record as Reunified. 
Once child record is flagged as Reunified, we can do the same for the confirmed enquiries (flag as reunified) and in doing so these enquiries would no longer appear in list of potential matches for other child records.

**Comment by baziwane** [comment]
GIVEN that I AM a FIELD WORKER
WHEN I am viewing a child record that has a confirmed matching enquiry
AND I flag the record as Reunited
THEN the corresponding confirmed enquiries should be tagged as Reunited

GIVEN that I am a FIELD WORKER
WHEN I am viewing an enquiry that was confirmed match to a child record
THEN I should be able to view a text that indicates that it's tagged as reunited

GIVEN that I am a FIELD WORKER
WHEN I am viewing potential matches to a child record
THEN I should see enquiries that haven't been tagged as reunited for other existing child records

**Comment by ctumwebaze** [comment]
Tasks
- [x] Add ability to mark an enquiry reunited.
- [x] Ensure that reunited enquiries don't show up as potential matches for other children records.
  - [x] Mark other potential matches associated with this enquiry as reunited-elsewhere.
  - [x] Ensure that no new potential matches are created for reunited enquiries
- [x] Add ability to mark an enquiry as reunited when the child is saved and marked as reunited. (See model callbacks)
- [x] Add ability to unmark a child and enquiry as reunited, and return all the other potential matches

**Comment by tomclement** [comment]
Still need to:
- [x]  Show which enquiries are reunited when viewing the list of enquiries. Tracking this in https://github.com/rapidftr/tracker/issues/245
- [ ] Display the reunited enquiry record when viewing a reunited child record. Tracking this in https://github.com/rapidftr/tracker/issues/244
