### ISSUE TITLE
Play Store APK

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#74]

**Comment by ctumwebaze** [comment]
Tasks
- [x] Configure Jenkins to automatically deploy to the CI
- [x] Generate a private key for signing the application
- [x] Create Maven profile for building a signed apk
- [x] Write the deployment script to deploy application to the play store.
- [x] Prepare screenshots
- [x] Prepare an EULA
- [x] Prepare an application Icon
- [x] Turn off Logging and Debugging(in the manifest file.)
- [x] Ensure proper permissions are set for the app (Consider removing the device admin permission - @tomclement)
- [x] Configure proper versioning in the app manifest
- [x] Ensure proper SDK versions are set in the manifest.
- [x] Figure out how to distribute the signing certificate and continuity.
- [x] Documentation
