### ISSUE TITLE
Release version 1.2.1

### ISSUE THREAD

**Issue by rdsubhas** [rapidftr/tracker#95]
##### Android:
- [x] Fix Android 4.2 bug #96 
- [x] Fix action items in #30
- [x] Hide Enquiries tab and disable enquiry sync
- [x] Branch off release 1.2.1 - https://github.com/rapidftr/RapidFTR---Android/releases
- [x] Build Signed APK
- [x] Make sure APK version numbers are correct
- [x] Upload APK to releases - http://bit.ly/rapidftr
##### Web:
- [x] Branch off release 1.2.1 - https://github.com/rapidftr/RapidFTR/releases
- [x] Make sure this works well with both Release 1.0 / 1.1 / 1.2 android phones on the field
-  Create upgrade guide (this release uses Chef, so best upgrade path is to setup a separate server, swap domain names, and then decomission old server)
-  Create NetBook installer and upload it to Releases, make sure upgrade process is documented
